version: "3.9"
services:
  Reclamation:
    container_name: reclamation-service-container
    build: .\
    ports:
      - "8085:8085"
    hostname: reclamationServer
    image: "reclamation-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - Eureka

  Room:
    container_name: room-service-container
    build: .\
    ports:
      - "8084:8084"
    hostname: roomServer
    image: "room-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - Eureka

  Reservation:
    container_name: reservation-service-container
    build: .\
    ports:
      - "8083:8083"
    hostname: reservationServer
    image: "reservation-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
      - spring.datasource.url=jdbc:mysql://docker-mysql_2:3306/gestionHotel?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - Eureka
      - docker-mysql_2

  docker-mysql_2:
      image: "mysql"
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
      ports:
        - 3306:3306
  Event:
    container_name: event-service-container
    build: .\
    ports:
      - "8086:8086"
    hostname: eventServer
    image: "event-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
      - spring.datasource.url=jdbc:mysql://docker-mysql_1:3306/gestionHotel?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - Eureka
      - docker-mysql_1

  docker-mysql_1:
    image: "mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3307:3306

  Employee:
    container_name: employee-service-container
    build: .\
    ports:
      - "8089:8089"
    hostname: employeeServer
    image: "employee-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
      - spring.datasource.url=jdbc:mysql://docker-mysql_3:3306/employeeDB?createDatabaseIfNotExist=true&useUnicode=true
    depends_on:
      - Eureka
      - docker-mysql_3

  docker-mysql_3:
    image: "mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3308:3306

  Eureka:
    container_name: erukaserver-container
    build: .\eurekaServer
    ports:
      - "8761:8761"
    hostname: eurekaServer
    image: "eurekaserver"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:8761/eureka/

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    hostname: key
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8180:8080
      - 8443:8443
    depends_on:
      - mysql-kc
    command:
      - start-dev

  mysql-kc:
    image: mysql:5.7.31
    ports:
      - 27021:27017
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  ApiGateway:
    container_name: apigatway
    build: .\
    ports:
      - "8090:8090"
    hostname: apiGateway
    image: "apigatway"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI= http://key:8180/realms/hotel-management-realm
    depends_on:
      - Eureka
      - keycloak
    links:
      - Eureka
      - Employee

  User:
    container_name: user
    build: .\
    ports:
      - "3000:3000"
    hostname: user
    image: "user-image"
    depends_on:
      - keycloak
      - Mongo
    command: "node app.js"

  Mongo:
    container_name: Mongo
    image: "mongo:5-focal"
    ports:
      - "27017:27017"
    hostname: Mongo
    depends_on:
      - "Eureka"

