version: "3.9"
services:
  Reclamation:
    container_name: reclamation-service-container
    build: .\
    ports:
      - "8085:8085"
    hostname: reclamationServer
    image: "reclamation-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - Eureka

  Room:
    container_name: room-service-container
    build: .\
    ports:
      - "8084:8084"
    hostname: roomServer
    image: "room-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - Eureka

  Reservation:
    container_name: reservation-service-container
    build: .\
    ports:
      - "8083:8083"
    hostname: reservationServer
    image: "reservation-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
      - spring.datasource.url=jdbc:mysql://docker-mysql_2:3306/gestionHotel?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - Eureka
      - docker-mysql_2

  docker-mysql_2:
      image: "mysql"
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
      ports:
        - 3306:3306
  Event:
    container_name: event-service-container
    build: .\
    ports:
      - "8086:8086"
    hostname: eventServer
    image: "event-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
      - spring.datasource.url=jdbc:mysql://docker-mysql_1:3306/gestionHotel?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - Eureka
      - docker-mysql_1

  docker-mysql_1:
    image: "mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3307:3306

  Eureka:
    container_name: erukaserver-container
    build: .\eurekaServer
    ports:
      - "8761:8761"
    hostname: eurekaServer
    image: "eurekaserver"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:8761/eureka/